### ISSUE TITLE
Site doesn't load on GitHub Pages.

### ISSUE THREAD

**Issue by rafi007akhtar** [hasnain003/fend-arcade-game#1]
I tried navigating to the following site, assuming it was hosted on GitHub Pages:
https://hasnain003.github.io/fend-arcade-game/

Turns out, it is, but it doesn't load.

**Reason.** In the file `js/app.js`, on line 45 there is the following code:
```
player.handleInput(allowedKeys[e.keyCode]);
```
However, no where in the file is the variable `player` declared or defined, nor does the file include any other JS file with the variable `player` in it for use, which is why the page doesn't load. You can confirm this error by tapping into the Developer Tools on Chrome and navigating to Console.

**Comment by hasnain003** [comment]
Thanks, It does now.
